version: "3.7"

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/backups
    environment:
      MYSQL_DATABASE: Stefan
      MYSQL_USER: Stefan
      MYSQL_PASSWORD: Stefan
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    restart: always

  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql

volumes:
  db_data: {}
